# Generated by Django 4.2.16 on 2024-11-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_group_id_alter_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='group_id',
            new_name='group',
        ),
    ]
